"""
ai_engine/orchestrator/pipeline.py

Defines the structured result object returned by the regulatory
verification pipeline.

The VerificationResult dataclass represents the final output produced
after a NAFDAC verification run. It captures the verification verdict,
supporting evidence retrieved from the database, and the reasoning
trace generated by the verification agent.

Instances of this class are created by ScanOrchestrator.verify()
after the regulatory verification agent completes its analysis.
"""

# Dataclass utilities used for defining structured result objects
from dataclasses import dataclass, field


@dataclass
class VerificationResult:
    """
    Structured result produced by a regulatory verification scan.

    This object contains the final verification decision together with
    supporting metadata retrieved from the database and the reasoning
    steps executed by the verification agent.

    Attributes:
        nafdac_no:
            The NAFDAC registration number provided for verification.

        scanned_category:
            Product category inferred from OCR or visual classification.

        verified:
            Boolean indicating whether the product passed all regulatory checks.

        verification_score:
            Numerical score representing verification confidence,
            typically ranging from 0.0 (no match) to 1.0 (fully verified).

        status_code:
            Machine-readable code describing the verification outcome.

        severity:
            Risk severity level assigned to the result.

        summary:
            Short human-readable message summarizing the verification result.

        detail:
            Expanded explanation describing the verification outcome.

        matched_record:
            Product record retrieved from the NAFDAC database that matches
            the scanned NAFDAC number, or None if no record was found.

        expiry_check:
            Structured result of the product expiry evaluation.

        alignment:
            Structured result of the subcategory alignment comparison
            between the scanned product and the registered product.

        reasoning_trace:
            Ordered list of reasoning steps generated by the verification
            agent during the verification process.

        tools_called:
            Ordered list of tool names invoked by the agent.

        fallback_used:
            Indicates whether the system used semantic retrieval as a
            fallback when the NAFDAC number lookup did not produce results.
    """

    # NAFDAC number used for the verification query
    nafdac_no: str

    # Product category inferred from scanning or classification
    scanned_category: str
    # Core verification verdict
    # Indicates whether the product successfully passed verification
    verified: bool

    # Confidence score representing verification strength
    verification_score: float

    # Status code representing the verification outcome
    status_code: str

    # Severity level associated with the verification result
    severity: str

    # Short summary of the verification result
    summary: str

    # Detailed explanation describing the verification decision
    detail: str
    # Product record retrieved from the database
    matched_record: dict | None

    # Result of the expiry validation step
    expiry_check: dict | None

    # Result of the category alignment analysis
    alignment: dict | None
    # Agent reasoning trace

    # Ordered list describing the reasoning steps taken by the agent
    reasoning_trace: list = field(default_factory=list)

    # Names of the tools invoked by the agent during reasoning
    tools_called: list = field(default_factory=list)

    # Indicates whether semantic fallback retrieval was used
    fallback_used: bool = False